language: node_js
node_js:
  - '0.12'
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 0ccc......7ff0
    secure: gwFOnbYs1qwj3q6mvODyuKmNO4h0MbQlQFUEJ7QRhqd0zFEaW20nnx9Ou3nQ2holVAwvZ2Mt52APERWRK65AG/jlcaJcM7VD1KI7P4wQAWNHnh2lL5OMZE73qYFsQuQkalOYFElFE3oFLlldO7qi8WZuOFFfoTPoYYRUF9mkf+4=
  on:
    tags: true
    repo: Brightspace/react-frau-intl
    all_branches: true
