language: node_js
node_js:
- '0.10'
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: OhE8z/8cuds2EncPOk+3yVvU/Ul5rq8qdaCqaNr2vFJQZJN9LxFaXzm4/zvcs0PMphJAGPc+t51Xz5x0u9+OopyxZ/pX0VFH6lNS67756nfsagPiJvjVAzMZA7sNCYFgLLF6ZMS9K1TvI0UErz2IPlnTt1MMnuFSgy1igII1qj8=
  on:
    tags: true
    repo: Brightspace/react-frau-intl
    all_branches: true

