language: node_js
node_js:
- '0.10'
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: S3VGRQQY3hLM9y89I9qHO9G7QfmSu6A43bC7lUEtf8M+zyZ5XTP22kEki+UI9PC0SMO/nCQTxhAyVE+m+6pNqbeWRzOrS2SWDLyD9KN7qIUl8VUWwaW7CQlHMrOppUuvJVxS9JNii0dSLcvwhtcb4eEB+LTSBNV3//VznHXeXc8=
  on:
    tags: true
    repo: Brightspace/react-frau-intl
    all_branches: true

